// wowskarma.app/src/app/shared/layout/footer/footer.component.ts
import { Component, Inject, OnInit } from "@angular/core";
import { environment } from "../../../../environments/environment";
import { ApiRegion } from "../../../models/ApiRegion";
import { AppConfigService } from "../../../services/app-config.service";

@Component({
  selector: "app-footer",
  templateUrl: "./footer.component.html",
  styleUrls: ["./footer.component.scss"],
})
export class FooterComponent implements OnInit {

  constructor(
    @Inject(AppConfigService) public appConfig: AppConfigService,
  ) {
  }

  public currentRegion: ApiRegion = AppConfigService.getApiRegionFromLocation() as ApiRegion;
  public currentApiHost: string = environment.apiHost[this.appConfig.currentRegion];

  ngOnInit(): void {
  }

}

<footer class="footer text-muted mt-5">
    <div class="container">
        <div class="row justify-content-between flex-grow-1">
            <div class="col-auto align-self-end">
                <div id="app-id">
                    <strong class="me-3">WOWS Karma ({{currentRegion}})</strong>
                    v{{appConfig.version}}
                </div>

                <div>
                    <ul class="list-inline">
                        <li class="list-inline-item"><a routerLink="/guidelines">Guidelines</a></li>
                        <li class="list-inline-item"><a target="_blank" rel="external" [href]="currentApiHost + '/swagger'">API</a></li>
                        <li class="list-inline-item"><a target="_blank" rel="external" href="https://github.com/SakuraIsayeki/WoWS-Karma">GitHub</a></li>
                        <li class="list-inline-item"><a target="_blank" rel="external" href="https://discord.gg/PrW9dtzK9K">Discord</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-auto align-self-end mb-3">
                Developed by <a href="https://wows-karma.com/player/503379282,Sakura_Isayeki">Sakura Isayeki</a>
                <br/>
                Powered by <a target="_blank" rel="external" href="https://nodsoft.net/">Nodsoft Systems</a>
            </div>
        </div>
    </div>
</footer>

// wowskarma.app/components/Footer.tsx
import Link from "next/link";
import {version as appVersion} from "../version";
import {container} from "tsyringe";
import {ApiRegion} from "../modules/api/ApiRegion";

const Footer = function () {
    return (
        <footer className="footer text-muted mt-5">
            <div className="container">
                <div className="row justify-content-between flex-grow-1">
                    <div className="col-auto align-self-end">
                        <div id="app-id">
                            <strong className="me-3">WOWS Karma ({container.resolve<ApiRegion>("currentRegion")})</strong>
                            v{appVersion}
                        </div>

                        <div>
                            <ul className="list-inline">
                                {getFooterLink("/guidelines", "Guidelines")}
                                {getFooterLink(new URL("/swagger", container.resolve<URL>("apiHost")).href, "API")}
                                {getFooterLink("https://github.com/SakuraIsayeki/WoWS-Karma", "GitHub")}
                                {getFooterLink("https://discord.gg/PrW9dtzK9K", "Discord")}
                            </ul>
                        </div>
                    </div>

                    <div className="col-auto align-self-end mb-3">
                        Developed by <a href="https://wows-karma.com/player/503379282,Sakura_Isayeki">Sakura Isayeki</a>
                        <br/>
                        Powered by <a target="_blank" href="https://nodsoft.net/" rel="noreferrer">Nodsoft Systems</a>
                    </div>
                </div>
            </div>
        </footer>
    )
};
export default Footer

function getFooterLink(href: string, text: string) {
    return (
        <li className="list-inline-item">
            <Link href={href} target={"_blank"}>{text}</Link>
        </li>
    )
}
