// wowskarma.app/src/app/shared/layout/navbar/navbar.component.ts
import { Component } from "@angular/core";
import { AuthService } from "src/app/services/auth.service";

@Component({
  selector: "app-navbar",
  templateUrl: "./navbar.component.html",
  styleUrls: ["./navbar.component.scss"],
})
export class NavbarComponent {
  public isCollapsed = true;

  constructor(public authService: AuthService) {
  }
}

<nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark-acrylic box-shadow mb-5 px-3">
  <div class="container-fluid ps-0">
    <div class="d-flex flex-row align-items-center mx-3">
      <a href="/" class='navbar-brand'>WOWS Karma</a>

      @switch (environmentName) {
        @case ("development") {
          <div><strong class="badge rounded-pill text-bg-warning text-uppercase">Dev</strong></div>
        }

        @case ("preview") {
          <div><strong class="badge rounded-pill text-bg-info text-uppercase">Preview</strong></div>
        }
      }
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavContent"
            (click)="isCollapsed = !isCollapsed" [attr.aria-expanded]="!isCollapsed"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbarNavContent" class="navbar-collapse collapse" [ngbCollapse]="isCollapsed">
      <ul class="navbar-nav flex-grow-1">
        <li class="nav-item"><a class="nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Home</a></li>
        <li class="nav-item"><a class="nav-link" routerLink="/player" routerLinkActive="active">Players</a></li>
        <li class="nav-item"><a class="nav-link" routerLink="/clan" routerLinkActive="active">Clans</a></li>
        <li class="nav-item"><a class="nav-link" routerLink="/posts" routerLinkActive="active">Posts</a></li>
      </ul>

      <ul class="navbar-nav flex-grow 0">
        <navbar-auth />

        <!-- TODO: Implement theming
        <li class="nav-item ml-3 msl-5">
          <button class="btn btn-link text-light">
            <i class="bi bi-moon" id="icon-theme-selector"></i>
          </button>
        </li>
        -->

        <li *ngIf="authService.userInfo$ | async" class="nav-item ml-3 msl-5">
          <app-notifications-button></app-notifications-button>
        </li>
      </ul>
    </div>
  </div>
</nav>

// wowskarma.app/components/Navbar.tsx
import Link from "next/link";
import NavLogin from "./NavLogin";

export default function Navbar() {
    return(
        <nav
            className="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-5 px-3">
            <div className="container-fluid ps-0">
                <div className="align-content-center mx-3">
                    <Link href="/"><a className='navbar-brand'>WOWS Karma</a></Link>
                </div>

                <div id="navbarNavContent" className="navbar-collapse collapse">
                    <ul className="navbar-nav flex-grow-1">
                        {getNavLinks([
                            { href: "/", text: "Home" },
                            { href: "/player", text: "Players" },
                            { href: "/clan", text: "Clans" },
                            { href: "/posts" , text: "Posts" },
                        ])}
                    </ul>

                    <ul className="navbar-nav flex-grow 0">
                        <NavLogin />

                        <li className="nav-item ml-3 msl-5">
                            <button className="btn btn-link text-light">
                                <i className="bi bi-moon" id="icon-theme-selector"></i>
                            </button>
                        </li>
                    </ul>
                </div>

                <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavContent">
                    <span className="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    )
}


/*
 * Generates HTML for a given array of links (href, text).
 */
function getNavLinks(links: Array<{href: string, text: string}>) {
    return links.map(link => getNavLink(link.href, link.text));
}

function getNavLink(href: string, text: string) {
    return (
        <li key={text} className="nav-item">
            <Link href={href}><a className="nav-link text-light">{text}</a></Link>
        </li>
    )
}
