// wowskarma.app/components/layout.tsx
import type { ReactElement } from "react";
import Navbar from "./navbar";
import Footer from "./footer";


export default function Layout({ children: content }: { children: ReactElement }) {
    return(
        <>
            <header>
                <Navbar />
            </header>

            <div className="container" style={{ marginTop: "100px !important" }}>
                <div id="psa-header" role="alert" className="mb-5">

                </div>

                <main role="main">
                    {content}
                </main>
            </div>

            <Footer />
        </>
    )
}

// wowskarma.app/src/app/shared/layout/layout.component.ts
import { Component, OnInit } from '@angular/core';
import { AppConfigService } from "../../services/app-config.service";

@Component({
  selector: 'app-layout',
  templateUrl: './layout.component.html',
  styleUrls: ['./layout.component.scss']
})
export class LayoutComponent {
  currentRegion: string = this.appConfigService.currentRegion;

  constructor(private appConfigService: AppConfigService) { }
}

<header>
    <app-navbar></app-navbar>
</header>

<div class="container-lg" style="margin-top: 100px !important">
    <div id="psa-header" role="alert" class="mb-5">
        <html-loader path="/assets/psa.global.html"></html-loader>
        <html-loader path="/assets/psa.{{currentRegion.toString().toLocaleLowerCase()}}.html"></html-loader>
    </div>

    <main role="main" class="my-5">
        <router-outlet></router-outlet>
    </main>
</div>

<app-footer></app-footer>
